// src/config/worlds.config.js
// 10 Curated Worlds for MosaicQuest (Grade 7 · Visual Patterns)

export const WORLDS = [
  {
    id: 0,
    name: "The First Motif",
    emoji: "🎭",
    accent: "var(--world-0)",
    description: "Spot and extend a repeating (cyclical) tile/shape pattern",
    conceptFocus: "identify-extend-repeating-pattern",
    boss: { name: "The Motif Muddler", emoji: "🎭", reward: "Apprentice Badge" },
  },
  {
    id: 1,
    name: "Growing or Repeating?",
    emoji: "🖼️",
    accent: "var(--world-1)",
    description: "Classify a visual pattern as growing or repeating and justify it",
    conceptFocus: "growing-vs-repeating",
    boss: { name: "The Category Critic", emoji: "🖼️", reward: "Classifier Badge" },
  },
  {
    id: 2,
    name: "Counting the Tiles",
    emoji: "🔢",
    accent: "var(--world-2)",
    description: "Count a quantity per figure in a growing pattern",
    conceptFocus: "represent-growing-pattern-numerically",
    boss: { name: "The Tile Counter", emoji: "🔢", reward: "Counter's Badge" },
  },
  {
    id: 3,
    name: "Straight Growth or Curved Growth?",
    emoji: "📈",
    accent: "var(--world-3)",
    description: "Visually compare constant vs. increasing growth",
    conceptFocus: "compare-growth-types",
    boss: { name: "The Growth Curve Ghost", emoji: "📈", reward: "Curve-Spotter Badge" },
  },
  {
    id: 4,
    name: "The Spinning Tile",
    emoji: "🌀",
    accent: "var(--world-4)",
    description: "Continue a pattern where a motif rotates each step",
    conceptFocus: "rotation-patterns",
    boss: { name: "The Spin Master", emoji: "🌀", reward: "Rotation Badge" },
  },
  {
    id: 5,
    name: "Mirror, Mirror",
    emoji: "🪞",
    accent: "var(--world-5)",
    description: "Continue a pattern involving reflected/flipped motifs",
    conceptFocus: "reflection-patterns",
    boss: { name: "The Mirror Phantom", emoji: "🪞", reward: "Reflection Badge" },
  },
  {
    id: 6,
    name: "Finding the Symmetry",
    emoji: "⚖️",
    accent: "var(--world-6)",
    description: "Identify line and rotational symmetry in a figure",
    conceptFocus: "symmetry-recognition",
    boss: { name: "The Symmetry Sentinel", emoji: "⚖️", reward: "Symmetry Badge" },
  },
  {
    id: 7,
    name: "Design the Far Tile",
    emoji: "🔭",
    accent: "var(--world-7)",
    description: "Predict/describe a specified far figure via spatial reasoning",
    conceptFocus: "predict-far-figure",
    boss: { name: "The Far Tile Rival", emoji: "🔭", reward: "Visionary Badge" },
  },
  {
    id: 8,
    name: "The Mosaic Commission",
    emoji: "🏛️",
    accent: "var(--world-8)",
    description: "Full applied multi-step design-and-justify scenario",
    conceptFocus: "multi-step-applied-visual-reasoning",
    boss: { name: "The Commission Critic", emoji: "🏛️", reward: "Master Artisan Badge" },
  },
  {
    id: 9,
    name: "The Grand Exhibition",
    emoji: "🖼️",
    accent: "var(--world-9)",
    description: "Mixed review of every concept above; hardest boss",
    conceptFocus: "mixed-review",
    boss: { name: "The Grand Curator", emoji: "👑", reward: "Gallery Champion Trophy" },
  },
];
